name: 'Gemini Issue Assistant'
description: 'Analyze GitHub issues using Gemini AI'
inputs:
  GEMINI_API_KEY:
    description: 'Gemini API key'
    required: true
  OTLP_GCP_WIF_PROVIDER:
    description: 'OTLP GCP WIF Provider'
    required: false
  OTLP_GOOGLE_CLOUD_PROJECT:
    description: 'OTLP Google Cloud Project'
    required: false
  prompt:
    description: 'Prompt for Gemini'
    required: true
  settings_json:
    description: 'Settings JSON'
    required: false
    default: '{}'

runs:
  using: 'composite'
  steps:
    - name: Install Gemini CLI
      shell: bash
      run: |
        curl -fsSL https://github.com/google-gemini/gemini-cli/releases/latest/download/gemini-cli-linux-amd64.tar.gz | tar -xz
        sudo mv gemini /usr/local/bin/
        chmod +x /usr/local/bin/gemini

    - name: Run Gemini Analysis
      shell: bash
      env:
        GEMINI_API_KEY: ${{ inputs.GEMINI_API_KEY }}
        OTLP_GCP_WIF_PROVIDER: ${{ inputs.OTLP_GCP_WIF_PROVIDER }}
        OTLP_GOOGLE_CLOUD_PROJECT: ${{ inputs.OTLP_GOOGLE_CLOUD_PROJECT }}
      run: |
        echo '${{ inputs.prompt }}' > prompt.txt
        echo '${{ inputs.settings_json }}' > settings.json
        gemini --prompt-file prompt.txt --settings-file settings.json
