name: Firebase Security Rules Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run_rules_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Firebase CLI and dependencies
      run: |
        npm install -g firebase-tools
        npm install --prefix functions @firebase/rules-unit-testing firebase-admin firebase-functions firebase

    - name: Install project dependencies
      run: npm install --prefix functions

    - name: Start Firebase Emulators and Run Tests
      run: |
        firebase emulators:exec --project peakactivity-test --only firestore "npm --prefix functions test functions/test/security/firestore.test.ts"
      env:
        FIRESTORE_EMULATOR_HOST: localhost:8080 

  security_scan_python:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Poetry
      run: pip install poetry

    - name: Install Python dependencies
      run: poetry install --no-root
      working-directory: aw-server

    - name: Run Bandit Security Scan
      run: poetry run bandit -r aw_server/ -ll -f json -o bandit-report.json
      working-directory: aw-server

    - name: Run Safety Dependency Scan
      run: poetry run safety check -r requirements.txt --full-report -o safety-report.json
      working-directory: aw-server

  security_scan_nodejs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Node.js dependencies
      run: npm install
      working-directory: aw-server/aw-webui

    - name: Run npm audit
      run: npm audit --json > npm-audit-report.json || true
      working-directory: aw-server/aw-webui 